[book]
authors = ["lzzsG"]
language = "en"
multilingual = false
src = "src"
title = "MIT-note"


[output.html]
site-url = "/MIT-note/"
default-theme = "black"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/lzzsG/MIT-note"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true