[book]
authors = ["lzzsG"]
language = "zh"
multilingual = false
src = "src"
title = "MIT Digital Systems Notebook"


[output.html]
default-theme = "black"
mathjax-support = true
preferred-dark-theme = "black"
git-repository-url = "https://github.com/lzzsG/MIT-digital-systems-notebook"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true
